### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Bots/PandaProtector#14]

**Comment by TinyPandas** [comment]
@M39a9am3R I'm not sure that we will gain much over converting to TS. 🤔 I will look into it again, just to be sure, but doesn't seem like it's worth the effort to do so.

**Comment by MathematicalDessert** [comment]
Arguably the project should've been started with Typescript support in mind. The project isn't large enough that converting isn't worth the time. I highly suggest you move to TS, as the benefits greatly outweigh the time costs.

**Comment by Dicey95** [comment]
It doesn't require much effort. Typescript is a superset of javascript, you could transfer your javascript code to typescript and have it working with a few minor adjustments.

**Comment by TinyPandas** [comment]
Closed with #30
