### ISSUE TITLE
You can ping people in commands

### ISSUE THREAD

**Issue by TestingPlant** [RSA-Bots/PandaProtector#24]
If a user does something such as `;sell @ @everyone`, they ping everyone, as it only seems to remove the first `@`.

**Comment by Raccoonyz** [comment]
trying to make a pull request for this fix

**Comment by widesteal321** [comment]
its literally just, this:
```js
message.channel.send(${itemQuery.replace('@', '')} is not a valid item.);
```
to this:
```js
message.channel.send(${itemQuery.replace(/@/g, '')} is not a valid item.);
```

or maybe even use something like this https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=cleanContent

**Comment by Raccoonyz** [comment]
see https://github.com/RSA-Bots/PandaProtector/pull/25

**Comment by TinyPandas** [comment]
Moved to https://github.com/RSA-Bots/AdventureBot
